#cloud-config
package_update: true
packages: ['squid']
runcmd:
  - curl "https://raw.githubusercontent.com/tssmits/servertools/master/servers/proxy/squid.acl.conf" > "/etc/squid/squid.acl.conf"
  - curl "https://raw.githubusercontent.com/tssmits/servertools/master/servers/proxy/squid.http_access.conf" > "/etc/squid/http_access.squid.conf"
  - curl "https://raw.githubusercontent.com/tssmits/servertools/master/servers/proxy/squid.conf" > "/etc/squid/squid.conf"
  - service squid restart
